Name:           ros-kinetic-tf
Version:        1.11.9
Release:        0%{?dist}
Summary:        ROS tf package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/tf
Source0:        %{name}-%{version}.tar.gz

Requires:       graphviz
Requires:       ros-kinetic-geometry-msgs
Requires:       ros-kinetic-message-filters >= 1.11.1
Requires:       ros-kinetic-message-runtime
Requires:       ros-kinetic-rosconsole
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-roswtf
Requires:       ros-kinetic-sensor-msgs
Requires:       ros-kinetic-std-msgs
Requires:       ros-kinetic-tf2-ros >= 0.5.16
BuildRequires:  ros-kinetic-angles
BuildRequires:  ros-kinetic-catkin >= 0.6.4
BuildRequires:  ros-kinetic-geometry-msgs
BuildRequires:  ros-kinetic-message-filters
BuildRequires:  ros-kinetic-message-generation
BuildRequires:  ros-kinetic-rosconsole
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-rostest
BuildRequires:  ros-kinetic-rostime
BuildRequires:  ros-kinetic-rosunit
BuildRequires:  ros-kinetic-sensor-msgs
BuildRequires:  ros-kinetic-std-msgs
BuildRequires:  ros-kinetic-tf2-ros >= 0.5.16

%description
tf is a package that lets the user keep track of multiple coordinate frames over
time. tf maintains the relationship between coordinate frames in a tree
structure buffered in time, and lets the user transform points, vectors, etc
between any two coordinate frames at any desired point in time. Migration: Since
ROS Hydro, tf has been &quot;deprecated&quot; in favor of tf2. tf2 is an
iteration on tf providing generally the same feature set more efficiently. As
well as adding a few new features. As tf2 is a major change the tf API has been
maintained in its current form. Since tf2 has a superset of the tf features with
a subset of the dependencies the tf implementation has been removed and replaced
with calls to tf2 under the hood. This will mean that all users will be
compatible with tf2. It is recommended for new work to use tf2 directly as it
has a cleaner interface. However tf will continue to be supported for through at
least J Turtle.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Sat Jul 15 2017 Tully Foote <tfoote@osrfoundation.org> - 1.11.9-0
- Autogenerated by Bloom

* Thu Mar 31 2016 Tully Foote <tfoote@osrfoundation.org> - 1.11.8-0
- Autogenerated by Bloom

