Name:           ros-jade-tf
Version:        1.11.4
Release:        0%{?dist}
Summary:        ROS tf package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/tf
Source0:        %{name}-%{version}.tar.gz

Requires:       graphviz
Requires:       ros-jade-geometry-msgs
Requires:       ros-jade-message-filters >= 1.11.1
Requires:       ros-jade-message-runtime
Requires:       ros-jade-rosconsole
Requires:       ros-jade-roscpp
Requires:       ros-jade-roswtf
Requires:       ros-jade-sensor-msgs
Requires:       ros-jade-std-msgs
Requires:       ros-jade-tf2 >= 0.4.5
Requires:       ros-jade-tf2-ros >= 0.4.5
BuildRequires:  ros-jade-angles
BuildRequires:  ros-jade-catkin >= 0.6.4
BuildRequires:  ros-jade-geometry-msgs
BuildRequires:  ros-jade-message-filters
BuildRequires:  ros-jade-message-generation
BuildRequires:  ros-jade-rosconsole
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-rostest
BuildRequires:  ros-jade-sensor-msgs
BuildRequires:  ros-jade-std-msgs
BuildRequires:  ros-jade-tf2 >= 0.5.4
BuildRequires:  ros-jade-tf2-ros >= 0.5.4

%description
tf is a package that lets the user keep track of multiple coordinate frames over
time. tf maintains the relationship between coordinate frames in a tree
structure buffered in time, and lets the user transform points, vectors, etc
between any two coordinate frames at any desired point in time.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Tue Jan 13 2015 Tully Foote <tfoote@osrfoundation.org> - 1.11.4-0
- Autogenerated by Bloom

