Name:           ros-indigo-geometry
Version:        1.11.9
Release:        0%{?dist}
Summary:        ROS geometry package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/geometry
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-angles
Requires:       ros-indigo-eigen-conversions
Requires:       ros-indigo-kdl-conversions
Requires:       ros-indigo-tf
Requires:       ros-indigo-tf-conversions
BuildRequires:  ros-indigo-catkin

%description
A metapackage for geometry library suite. Migration: Since ROS Hydro, tf has
been &quot;deprecated&quot; in favor of tf2. tf2 is an iteration on tf providing
generally the same feature set more efficiently. As well as adding a few new
features. As tf2 is a major change the tf API has been maintained in its current
form. Since tf2 has a superset of the tf features with a subset of the
dependencies the tf implementation has been removed and replaced with calls to
tf2 under the hood. This will mean that all users will be compatible with tf2.
It is recommended for new work to use tf2 directly as it has a cleaner
interface. However tf will continue to be supported for through at least J
Turtle.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sat Jul 15 2017 Tully Foote <tfoote@osrfoundation.org> - 1.11.9-0
- Autogenerated by Bloom

* Fri Mar 04 2016 Tully Foote <tfoote@osrfoundation.org> - 1.11.8-0
- Autogenerated by Bloom

* Tue Apr 21 2015 Tully Foote <tfoote@osrfoundation.org> - 1.11.7-0
- Autogenerated by Bloom

* Wed Mar 25 2015 Tully Foote <tfoote@osrfoundation.org> - 1.11.6-0
- Autogenerated by Bloom

* Tue Mar 17 2015 Tully Foote <tfoote@osrfoundation.org> - 1.11.5-0
- Autogenerated by Bloom

* Tue Dec 23 2014 Tully Foote <tfoote@osrfoundation.org> - 1.11.4-0
- Autogenerated by Bloom

